// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHmmj8IscnhVH1becZ0QCoDpanidBtAm0',
    appId: '1:568957344274:web:ba1649667b4e22631fd6cb',
    messagingSenderId: '568957344274',
    projectId: 'testagriapp',
    authDomain: 'testagriapp.firebaseapp.com',
    storageBucket: 'testagriapp.appspot.com',
    measurementId: 'G-4TNZ39DK8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuI836OZCaqHG6T_FIMxhJ2aC73ykCZJE',
    appId: '1:568957344274:android:8fdcb4d2d17aa5121fd6cb',
    messagingSenderId: '568957344274',
    projectId: 'testagriapp',
    storageBucket: 'testagriapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNH1fW79qt-aUSm2tCXdZ8JB1dDrtQ-o',
    appId: '1:568957344274:ios:ee69cbd0493076831fd6cb',
    messagingSenderId: '568957344274',
    projectId: 'testagriapp',
    storageBucket: 'testagriapp.appspot.com',
    iosBundleId: 'com.example.testagriapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNH1fW79qt-aUSm2tCXdZ8JB1dDrtQ-o',
    appId: '1:568957344274:ios:516ffb62542d988a1fd6cb',
    messagingSenderId: '568957344274',
    projectId: 'testagriapp',
    storageBucket: 'testagriapp.appspot.com',
    iosBundleId: 'com.example.testagriapp.RunnerTests',
  );
}
